/**
 * This script was generated by Loon to simulate http requests.
 */

let url = "https://missav.ai/mdb-816-uncensored-leak";
let headers = {
    'cookie':['_ga_0C6GHNFYBF=GS2.1.s1752923272$o1$g0$t1752923279$j53$l0$h0','_ga=GA1.1.207309372.1752923272','VK1EPv29cpkMorv5XtizRbBLs5GxnaIJ8cQYGNnl=eyJpdiI6IklsVjE2dEp0MXAzbS9SdmdoZ2taeEE9PSIsInZhbHVlIjoibElET05zSHZ6amk5WllmOTJCSzF4ZmRzM09lQmo1WnlJRFRHeDdDcDhOZXFySXVkdmhpZ2VNTWZKL202VDlaUUNvQ1hCTHFIT2poQndUbjUxL0RWcXMweE1Nb0ZYckh4bEptREVpUFVndXczZXZQVG01NkdnTG9HV2N0S0lxRDlhckZRc0xCR2FXb2RDWXVqbEZHM0JCZkxsRFJuN3FSMVVXcHJuM2wxc25uVDFhZ20rVCtoRUNKNk5ITmVvc0FZZGtsdk55RGlvYWtSaW91bXBCNXFrUGlKQVFmc3M5enpxWmsrTlIreEtwL2g5WmJUa2FJV0lPOWhhMzlJdktYd3dXdlo5NFpiN1c1akkyTzZTNXpLdS9sa0JQZ0t0MUpyZFZZekdqUkFiSDRhd3Jtb0h3MHQxbFZ6QU9FcHF6TmdnMlVWWC8weHdhb0xWVmNzL0N0dFh6UmJOUXROQ0xJc0dxcDhHMG5SeHNkc1l3TzQveWhYYklzc2ZBMERJRmVEVmFEWmlncFk3NmNRN29mb1JmWXlmdz09IiwibWFjIjoiOTAxYzI1NjY1Y2FjZThkMzYzZmRjMzhhZTZkZTIxYjU4ZmJlZWViZWJhZTAzZTdjN2I0NGRiYjg1OTNjNmI2ZiIsInRhZyI6IiJ9','XSRF-TOKEN=eyJpdiI6Ik9NMVo3Ky9NelhFTUFGb2tGZkEvWEE9PSIsInZhbHVlIjoidHhaQjNkOHRMUkwvUXJOaVdNdEtnOEpnMWJnbmxRTFBpMHNqSFFvbWRyYmVwKzdzeXhONVF5TjQzY3VwTWFkNWRFNjZsS1Mxd2pJWXFiUXI2eE9NdVN5QlIwa2ZocE9mZDRXSnNkdkRjdEhxWXdTODJCRWZRZ2Y4Y3ZrL01RejIiLCJtYWMiOiJiNjE0MDE2NjQyN2YwMjQ3OThiYzgyMjI0NDVjNjM3OThiOTAxOTAwODEzNWMwMzliNDg0YjFjOTExYzgwNjE3IiwidGFnIjoiIn0%3D','missav_session=eyJpdiI6IlVlaDB2QXdOTzUvaDYvUk5PZ3N3Mnc9PSIsInZhbHVlIjoidFRHUmdZU2g0dk1sT0Y5ME1GaS8zMk8vaW8rOGw4MTdGelpTS05zKzdqRWF0WnMyb2wzcnNpT3h4cUFEZGtvdTVQOURIY0tNaGxnZ1JKSk5IMEJpRGpEQlJDL0h1TnFDWlhyTVdaQTlpQmVXUWdDd1VPSWtEUjdWMmp5a3lBTkoiLCJtYWMiOiJmNWI0ZjAwZmZkYzFiOTY0NDNhYmRkZmM4MzNjYmM4MTZjMWY2MWJkY2Q5MmZiOWY5Yzc3Zjc0YjFiNzk5NmMyIiwidGFnIjoiIn0%3D','cf_clearance=aGtFrIUiTCmhPhTQ358XtqPoCtyZfgc3HA5P5EF2pmA-1752923272-1.2.1.1-hEQtphGui4CYV4yYGKrxv9x8Se9aPaR2jKVGQUrVknm7WSNKqRMLxuvs9JKoSYhr9YE.tmPwGUQD7yIOoPwGAU2jb22iabJ5clR9AfAVzkqh30P8lnNp0UubmIung1KgPklz9OQjVaf7.ErEzPqxdD1RrBMvbtohm7K336QYrhlvw0Pj39w_Mz7AvO8igjiz64ILE.niIpOZioR_la9X3MI5PiaWv.gkTI4QaIstCpj5MCxhK_gyeUJaeisWdq2L','user_uuid=3c8ba7f4-edf0-46ae-bea3-0312b15f213f'],
    'user-agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1',
    'accept-language':'zh-CN,zh-Hans;q=0.9',
    'accept-encoding':'gzip, deflate, br',
    'sec-fetch-dest':'document',
    'referer':'https://missav.ai/cjod-257-uncensored-leak',
    'accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'sec-fetch-mode':'navigate',
    'sec-fetch-site':'same-origin',
};

var params = {
    url:url,
    timeout:5000,
    headers:headers,
    alpn:'h2',
};

$httpClient.get(params, function(errormsg,response,data) {
    if (errormsg) {
        console.log(errormsg);
    } else {
        console.log("Response Status: " + response.status);
        console.log("Response Headers: " + JSON.stringify(response.headers));
        console.log("Response Body: " + data);
    }
    $done();
});
